services:
  - name: laravel
    plan: starter
    buildCommand: |
      cp .env.example .env
      composer install --ignore-platform-reqs
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
    env:
      - key: APP_KEY
        generateValue: true
